spring:
  datasource:
    username: root
    password: Sayuru123**
    url: jdbc:mysql://localhost:3306/jrtp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com  # Replace with your Gmail email address
    password: your_email_password   # Replace with your Gmail app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher